### PR TITLE
books added for C

### PR DESCRIPTION
**Pull request by devsks**
I would really like to add more book in my knowledge to help enhance the content of the repository.
_**I have added two books in C**_. Please review it and accept my pull request.

### CODE REVIEW

**Comment by sourabhtk37** [comment]
It shouldn't be of concern but changing license is not required. The creator/owner of the repo is the one who have copyright rights. Please change the PR.
If there is a reason for changing LICENSE file, then please share.

**Comment by devsks** [comment]
I think I got confused because at first the name mentioned in the license was **devupin** and then it was changed to **Manu**. Since I am a beginner in open source projects I thought after forking we need to update the license file with our name. 
I have changed the PR @sourabhtk37  please review it again.

**Comment by sourabhtk37** [comment]
Looks good to me. Thanks :heart:

**Comment by devsks** [comment]
Thanks @sourabhtk37. This will be my first contribution to an open source project. If approved 😀

**Comment by devsks** [comment]
cc: @manuraj17

**Pull request merged**
